### ISSUE TITLE
CustomerRegisterSubscriber can break address change

### ISSUE THREAD

**Issue by bethlehemit** [paynl/shopware6-plugin#139]
Hi,

When a customers address gets modified through a non web request, the CustomerRegisterSubscriber class throws a nullpointer exception on $request not being set

Suggested fix:
diff --git a/vendor/store.shopware.com/paynlpaymentshopware6/src/Subscriber/CustomerRegisterSubscriber.php b/vendor/store.shopware.com/paynlpaymentshopware6/src/Subscriber/CustomerRegisterSubscriber.php
index 8703e99..846572a 100644
--- a/vendor/store.shopware.com/paynlpaymentshopware6/src/Subscriber/CustomerRegisterSubscriber.php
+++ b/vendor/store.shopware.com/paynlpaymentshopware6/src/Subscriber/CustomerRegisterSubscriber.php
@@ -53,6 +53,11 @@ class CustomerRegisterSubscriber implements EventSubscriberInterface
         if ($this->counter < 1) {
             $this->counter++;
             $request = $this->requestStack->getMasterRequest();
+
+            if (is_null($request)) {
+                return; #CLI job
+            }
+
             $cocNumber = $request->get('coc_number');
             $addressIdArray = $event->getIds();
             $context = $event->getContext();

**Comment by ahudyma** [comment]
Thanks! We hope to include this fix in our next release https://github.com/paynl/shopware6-plugin/pull/141

**Comment by belendel** [comment]
Same issue. When is 1.3.3 scheduled?
