### ISSUE TITLE
Account > Profile issue since (at least) version 1.3.5

### ISSUE THREAD

**Issue by thompalstra** [paynl/shopware6-plugin#190]
In the PayNL the following template is overwritten:

`PaynlPaymentShopware6/src/Resources/views/storefront/page/account/profile/index.html.twig`

This causes the My Account > My Profile (/account/profile) page to lose 

it's functionality for frontend users such as changing passwords, changing email addresses.

How PayNL renders the page:
![incorrect_page](https://user-images.githubusercontent.com/17644484/132659271-e0e31f0f-aa65-4c32-a6cc-d9b215d66f6a.PNG)

How the page should be rendered:\
![correct_page](https://user-images.githubusercontent.com/17644484/132659265-a1def786-e880-4cdb-9a92-2a3b8158d1d3.PNG)

Can you guys make this an urgent issue? This has caused most of our customers (and even us developers included) to believe Shopware 6 doesn't even provide this functionality while it's caused by this overwritten template.

**Comment by ahudyma** [comment]
Hi! Thanks for reporting this. Let us check

**Comment by ahudyma** [comment]
Please check this release https://github.com/paynl/shopware6-plugin/releases/tag/v1.4.6 and let us know if it has fixed your issue

**Comment by thompalstra** [comment]
@ahudyma this indeed resolves the issue. In stead of overriding the entire block, overriding only that specific form was the fix.

Is there any indication when this "new version" will be available via the Shopware 6 store?

**Comment by ahudyma** [comment]
It is 'live' in store since yesterday
