### ISSUE TITLE
shopware 6.5 support?

### ISSUE THREAD

**Issue by shopworksnl** [paynl/shopware6-plugin#258]
Hi,

Any idea when you'll support the latest shopware 6.5 version?

I'm getting an You have requested a non-existent service "session". error when activating/install the latest plugin (1.4.19) with the latest version of shopware (6.5.1.1).

Thanks,
Ron

**Comment by escruickshank** [comment]
Hi Ron, thank you for your question. We are working on this as we speak and expecting to release an update shortly.

**Comment by escruickshank** [comment]
Hi Ron @shopworksnl, we have just released v1.5.0. This version is compatible with Shopware 6.4 and 6.5. Please let me know whether this meets your needs.
