### ISSUE TITLE
Breaking require_once statement

### ISSUE THREAD

**Issue by wmouwen** [paynl/shopware6-plugin#279]
## Problem

The plugin registration file contains a `require_once` statement. It relies on the assumption that a `vendor` directory exists as parent of the plugin's installation.

https://github.com/paynl/shopware6-plugin/blob/3d1b173335964405fd6b5b1850f9b9f5da49da60/src/PaynlPaymentShopware6.php#L5-L7

This filepath doesn't necessarily exist for all possible installation options of the plugin. When installing plugins through the command line or through `composer.json`, the `vendor` directory will live a level higher than this plugin expects.

```
<project>
├── composer.json
├── src
└── vendor
    └── paynl
        └── shopware6-plugin
            ├── composer.json
            ├── src
            │   └── PaynlPaymentShopware6.php
            └── <missing vendor dir>
```

## Request

Can the `require_once` statement be removed from the code? If it is needed elsewhere, can it be moved to a bootstrapping script so it doesn't impact production?

## Workaround

A possible workaround is to remove the breaking statement using `sed` ([docs](https://www.gnu.org/software/sed/manual/sed.html)) in a post-install and post-update script in Composer.

```json
{
  "config": {
    "allow-plugins": {
      "symfony/runtime": true,
      "symfony/flex": true
    }
  },
  "require": {
    "shopware/core": "~6.4",
    "paynl/shopware6-plugin": "^1.4"
  },
  "repositories": [
    {
      "type": "vcs",
      "url": "git@github.com:paynl/shopware6-plugin.git"
    }
  ],
  "scripts": {
    "post-install-cmd": [
      "sed '/vendor\\/autoload\\.php/d' --in-place ./vendor/paynl/shopware6-plugin/src/PaynlPaymentShopware6.php"
    ],
    "post-update-cmd": [
      "sed '/vendor\\/autoload\\.php/d' --in-place ./vendor/paynl/shopware6-plugin/src/PaynlPaymentShopware6.php"
    ]
  }
}
```

**Comment by escruickshank** [comment]
Hi! Thank you for raising this with us. We will fix this and let you know once updated. Your feedback is appreciated.
