### ISSUE TITLE
Service definition incorrect

### ISSUE THREAD

**Issue by wmouwen** [paynl/shopware6-plugin#320]
The config defines a service called `PaynlAccountOrderController`.

https://github.com/paynl/shopware6-plugin/blob/78e0d210334e51eec836e09c1eab574969985de4/src/Resources/config/compatibility/controller/sw65/controller.xml#L14

The service it tries to declare is called `AccountOrderController` without the `Paynl` prefix.

https://github.com/paynl/shopware6-plugin/blob/78e0d210334e51eec836e09c1eab574969985de4/src/Controller/Storefront/AccountOrder/Sw65/AccountOrderController.php#L11

This is cause for a misconfiguration in the container. When you run Symfony's linter, it shows up as an error.

```shell
> bin/console lint:container

In AbstractRecursivePass.php line 176:
                                                                                                                                       
  [Symfony\Component\DependencyInjection\Exception\RuntimeException]                                                                   
  Invalid service "PaynlPayment\Shopware6\Controller\Storefront\AccountOrder\Sw65\PaynlAccountOrderController": class "PaynlPayment\S  
  hopware6\Controller\Storefront\AccountOrder\Sw65\PaynlAccountOrderController" does not exist.                                        
                                                                                                                                       
```

**Comment by escruickshank** [comment]
Hi @wmouwen, thank you for the clear information provided! We will look into this shortly.

**Comment by escruickshank** [comment]
Hi @wmouwen, we have renamed the classname and will include this in our next release. Thank you for your input!

**Comment by wmouwen** [comment]
Thanks for the quick resolution @escruickshank and @szhalba-sm. Do you have any expectations on the release date?

**Comment by escruickshank** [comment]
Hi @wmouwen we are preparing a new release this week.
