### ISSUE TITLE
Payment cancel results in empty cart

### ISSUE THREAD

**Issue by michielkalle** [paynl/shopware6-plugin#338]
When cancelling a payment using the redirect button of the selected bank will result in a redirect back to the shop url:
`/account/order/edit/{orderId}?error-code={errrorCode}`
And that is correct.

But when using the back button of the browser you got redirected to `/checkout/confirm`
This results in an empty cart and an resetted checkout. This issue is unfortunately a native Shopware functionality.

Could you make sure the back button of the browser also redirects back to the`/account/order/edit/{orderId}?error-code={errrorCode}` to fix empty cart issues?

**Comment by woutse** [comment]
Thanks for your message. We'll look into it.

**Comment by woutse** [comment]
Update: We can fix this. Probably available in release 1.6.1. We'll let you know.

**Comment by woutse** [comment]
Release 1.6.1 is out, this one should fix this problem.
